apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fluxcd.io/sync-checksum: 1179a121367fac0009852335a564c7f0e1466cbf
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"fluxcd.io/sync-checksum":"1179a121367fac0009852335a564c7f0e1466cbf"},"labels":{"app":"podinfo","fluxcd.io/sync-gc-mark":"sha256.qy1MFDKg4IHW6EIJwrg-hfxOfIJXL8JvGYKVXWZ4rDQ"},"name":"podinfo","namespace":"default"},"spec":{"ports":[{"name":"http","port":9898,"protocol":"TCP","targetPort":"http"},{"name":"grpc","port":9999,"protocol":"TCP","targetPort":"grpc"}],"selector":{"app":"podinfo"},"type":"ClusterIP"}}
    creationTimestamp: "2020-03-30T09:55:15Z"
    labels:
      app: podinfo
      fluxcd.io/sync-gc-mark: sha256.qy1MFDKg4IHW6EIJwrg-hfxOfIJXL8JvGYKVXWZ4rDQ
    name: podinfo
    namespace: default
    resourceVersion: "748"
    selfLink: /api/v1/namespaces/default/services/podinfo
    uid: 8deb796d-726c-11ea-8426-122aca9cacdb
  spec:
    clusterIP: 10.109.169.182
    ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 9999
      protocol: TCP
      targetPort: grpc
    selector:
      app: podinfo
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      fluxcd.io/sync-checksum: 11e71a6588b83424606a0da24357e4fed2d3e4fd
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"fluxcd.io/sync-checksum":"11e71a6588b83424606a0da24357e4fed2d3e4fd"},"labels":{"app":"podinfo","fluxcd.io/sync-gc-mark":"sha256.Dl0oEtxMHTwVCPnu2FRkXX0_TMjO5SphJFQcCD7MTF8"},"name":"podinfo","namespace":"default"},"spec":{"minReadySeconds":3,"progressDeadlineSeconds":60,"revisionHistoryLimit":5,"selector":{"matchLabels":{"app":"podinfo"}},"strategy":{"rollingUpdate":{"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"prometheus.io/port":"9797","prometheus.io/scrape":"true"},"labels":{"app":"podinfo"}},"spec":{"containers":[{"command":["./podinfo","--port=9898","--port-metrics=9797","--grpc-port=9999","--grpc-service-name=podinfo","--level=info","--random-delay=false","--random-error=false"],"env":[{"name":"PODINFO_UI_COLOR","value":"#34577c"}],"image":"stefanprodan/podinfo:3.2.1","imagePullPolicy":"IfNotPresent","livenessProbe":{"exec":{"command":["podcli","check","http","localhost:9898/healthz"]},"initialDelaySeconds":5,"timeoutSeconds":5},"name":"podinfod","ports":[{"containerPort":9898,"name":"http","protocol":"TCP"},{"containerPort":9797,"name":"http-metrics","protocol":"TCP"},{"containerPort":9999,"name":"grpc","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["podcli","check","http","localhost:9898/readyz"]},"initialDelaySeconds":5,"timeoutSeconds":5},"resources":{"limits":{"cpu":"2000m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"64Mi"}}}]}}}}
    creationTimestamp: "2020-03-30T09:55:15Z"
    generation: 2
    labels:
      app: podinfo
      fluxcd.io/sync-gc-mark: sha256.Dl0oEtxMHTwVCPnu2FRkXX0_TMjO5SphJFQcCD7MTF8
    name: podinfo
    namespace: default
    resourceVersion: "1156"
    selfLink: /apis/apps/v1/namespaces/default/deployments/podinfo
    uid: 8e0a999c-726c-11ea-8426-122aca9cacdb
  spec:
    minReadySeconds: 3
    progressDeadlineSeconds: 60
    replicas: 2
    revisionHistoryLimit: 5
    selector:
      matchLabels:
        app: podinfo
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        annotations:
          prometheus.io/port: "9797"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          app: podinfo
      spec:
        containers:
        - command:
          - ./podinfo
          - --port=9898
          - --port-metrics=9797
          - --grpc-port=9999
          - --grpc-service-name=podinfo
          - --level=info
          - --random-delay=false
          - --random-error=false
          env:
          - name: PODINFO_UI_COLOR
            value: '#34577c'
          image: stefanprodan/podinfo:3.2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:9898/healthz
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: podinfod
          ports:
          - containerPort: 9898
            name: http
            protocol: TCP
          - containerPort: 9797
            name: http-metrics
            protocol: TCP
          - containerPort: 9999
            name: grpc
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:9898/readyz
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "2"
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2020-03-30T09:57:57Z"
      lastUpdateTime: "2020-03-30T09:57:57Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-03-30T09:57:44Z"
      lastUpdateTime: "2020-03-30T09:57:57Z"
      message: ReplicaSet "podinfo-84578c58cc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: autoscaling/v2beta1
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      fluxcd.io/sync-checksum: 0928901fe11858ba53e0c36104e1329c6dd50481
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{"fluxcd.io/sync-checksum":"0928901fe11858ba53e0c36104e1329c6dd50481"},"labels":{"fluxcd.io/sync-gc-mark":"sha256.ST3a_tjg9ti4yyniDUtMbT_-7Gt-tk27BAQ6X8deIbU"},"name":"podinfo","namespace":"default"},"spec":{"maxReplicas":4,"metrics":[{"resource":{"name":"cpu","targetAverageUtilization":99},"type":"Resource"}],"minReplicas":2,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"podinfo"}}}
    creationTimestamp: "2020-03-30T09:55:15Z"
    labels:
      fluxcd.io/sync-gc-mark: sha256.ST3a_tjg9ti4yyniDUtMbT_-7Gt-tk27BAQ6X8deIbU
    name: podinfo
    namespace: default
    resourceVersion: "837"
    selfLink: /apis/autoscaling/v2beta1/namespaces/default/horizontalpodautoscalers/podinfo
    uid: 8e2dca90-726c-11ea-8426-122aca9cacdb
  spec:
    maxReplicas: 4
    metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 99
      type: Resource
    minReplicas: 2
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: podinfo
  status:
    conditions:
    - lastTransitionTime: "2020-03-30T09:55:33Z"
      message: the HPA controller was able to get the target's current scale
      reason: SucceededGetScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2020-03-30T09:55:48Z"
      message: 'the HPA was unable to compute the replica count: unable to get metrics
        for resource cpu: unable to fetch metrics from resource metrics API: the server
        could not find the requested resource (get pods.metrics.k8s.io)'
      reason: FailedGetResourceMetric
      status: "False"
      type: ScalingActive
    currentMetrics: null
    currentReplicas: 2
    desiredReplicas: 2
    lastScaleTime: "2020-03-30T09:55:33Z"
kind: List
metadata: {}
